2022-03-26 17:15:32,956 INFO    MainThread:57604 [internal.py:wandb_internal():92] W&B internal server running at pid: 57604, started at: 2022-03-26 17:15:32.956776
2022-03-26 17:15:32,959 INFO    WriterThread:57604 [datastore.py:open_for_write():77] open: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\run-3f1joo08.wandb
2022-03-26 17:15:32,963 DEBUG   SenderThread:57604 [sender.py:send():235] send: header
2022-03-26 17:15:32,963 DEBUG   SenderThread:57604 [sender.py:send():235] send: run
2022-03-26 17:15:36,370 ERROR   SenderThread:57604 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\app\conda\envs\pytorch\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\app\conda\envs\pytorch\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\app\conda\envs\pytorch\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\app\conda\envs\pytorch\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\wandb\sdk\internal\internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2022-03-26 17:15:41,641 INFO    SenderThread:57604 [dir_watcher.py:__init__():169] watching files in: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files
2022-03-26 17:15:41,641 INFO    SenderThread:57604 [sender.py:_start_run_threads():812] run started: 3f1joo08 with start time 1648286132
2022-03-26 17:15:41,662 DEBUG   SenderThread:57604 [sender.py:send():235] send: summary
2022-03-26 17:15:41,662 INFO    SenderThread:57604 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-03-26 17:15:41,662 DEBUG   HandlerThread:57604 [handler.py:handle_request():141] handle_request: check_version
2022-03-26 17:15:41,663 DEBUG   SenderThread:57604 [sender.py:send_request():249] send_request: check_version
2022-03-26 17:15:42,238 DEBUG   HandlerThread:57604 [handler.py:handle_request():141] handle_request: run_start
2022-03-26 17:15:42,249 DEBUG   HandlerThread:57604 [meta.py:__init__():37] meta init
2022-03-26 17:15:42,249 DEBUG   HandlerThread:57604 [meta.py:__init__():51] meta init done
2022-03-26 17:15:42,249 DEBUG   HandlerThread:57604 [meta.py:probe():211] probe
2022-03-26 17:15:42,255 DEBUG   HandlerThread:57604 [meta.py:_save_pip():55] save pip
2022-03-26 17:15:42,256 DEBUG   HandlerThread:57604 [meta.py:_save_pip():69] save pip done
2022-03-26 17:15:42,256 DEBUG   HandlerThread:57604 [meta.py:_save_conda():76] save conda
2022-03-26 17:15:42,646 INFO    Thread-12 :57604 [dir_watcher.py:_on_file_created():217] file/dir created: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\wandb-summary.json
2022-03-26 17:15:42,646 INFO    Thread-12 :57604 [dir_watcher.py:_on_file_created():217] file/dir created: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\requirements.txt
2022-03-26 17:15:42,647 INFO    Thread-12 :57604 [dir_watcher.py:_on_file_created():217] file/dir created: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\conda-environment.yaml
2022-03-26 17:15:45,430 DEBUG   HandlerThread:57604 [meta.py:_save_conda():86] save conda done
2022-03-26 17:15:45,430 DEBUG   HandlerThread:57604 [meta.py:probe():249] probe done
2022-03-26 17:15:45,436 DEBUG   SenderThread:57604 [sender.py:send():235] send: files
2022-03-26 17:15:45,436 INFO    SenderThread:57604 [sender.py:_save_file():947] saving file wandb-metadata.json with policy now
2022-03-26 17:15:45,442 DEBUG   HandlerThread:57604 [handler.py:handle_request():141] handle_request: stop_status
2022-03-26 17:15:45,442 DEBUG   SenderThread:57604 [sender.py:send_request():249] send_request: stop_status
2022-03-26 17:15:45,665 INFO    Thread-12 :57604 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\conda-environment.yaml
2022-03-26 17:15:45,665 INFO    Thread-12 :57604 [dir_watcher.py:_on_file_created():217] file/dir created: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\output.log
2022-03-26 17:15:45,665 INFO    Thread-12 :57604 [dir_watcher.py:_on_file_created():217] file/dir created: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\wandb-metadata.json
2022-03-26 17:15:45,730 DEBUG   SenderThread:57604 [sender.py:send():235] send: telemetry
2022-03-26 17:15:46,347 INFO    Thread-16 :57604 [upload_job.py:push():137] Uploaded file C:\Users\chris\AppData\Local\Temp\tmp8utmzvpbwandb\fqoxx34i-wandb-metadata.json
2022-03-26 17:15:47,680 INFO    Thread-12 :57604 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\output.log
2022-03-26 17:16:00,742 DEBUG   HandlerThread:57604 [handler.py:handle_request():141] handle_request: stop_status
2022-03-26 17:16:00,742 DEBUG   SenderThread:57604 [sender.py:send_request():249] send_request: stop_status
2022-03-26 17:16:03,792 INFO    Thread-12 :57604 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\config.yaml
2022-03-26 17:16:13,191 DEBUG   SenderThread:57604 [sender.py:send():235] send: stats
2022-03-26 17:16:16,032 DEBUG   HandlerThread:57604 [handler.py:handle_request():141] handle_request: stop_status
2022-03-26 17:16:16,033 DEBUG   SenderThread:57604 [sender.py:send_request():249] send_request: stop_status
2022-03-26 17:16:30,459 WARNING MainThread:57604 [internal.py:wandb_internal():155] Internal process interrupt: 1
2022-03-26 17:16:31,473 WARNING MainThread:57604 [internal.py:is_dead():387] Internal process exiting, parent pid 21816 disappeared
2022-03-26 17:16:31,473 ERROR   MainThread:57604 [internal.py:wandb_internal():151] Internal process shutdown.
2022-03-26 17:16:32,372 INFO    WriterThread:57604 [datastore.py:close():281] close: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\run-3f1joo08.wandb
2022-03-26 17:16:32,450 INFO    HandlerThread:57604 [handler.py:finish():778] shutting down handler
2022-03-26 17:16:32,450 INFO    SenderThread:57604 [sender.py:finish():1078] shutting down sender
2022-03-26 17:16:32,451 INFO    SenderThread:57604 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-26 17:16:33,043 INFO    SenderThread:57604 [dir_watcher.py:finish():313] scan: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files
2022-03-26 17:16:33,044 INFO    SenderThread:57604 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\conda-environment.yaml conda-environment.yaml
2022-03-26 17:16:33,045 INFO    SenderThread:57604 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\config.yaml config.yaml
2022-03-26 17:16:33,045 INFO    SenderThread:57604 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\output.log output.log
2022-03-26 17:16:33,046 INFO    SenderThread:57604 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\requirements.txt requirements.txt
2022-03-26 17:16:33,052 INFO    SenderThread:57604 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\wandb-metadata.json wandb-metadata.json
2022-03-26 17:16:33,056 INFO    SenderThread:57604 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\wandb-summary.json wandb-summary.json
2022-03-26 17:16:33,084 INFO    SenderThread:57604 [file_pusher.py:finish():145] shutting down file pusher
2022-03-26 17:16:33,085 INFO    SenderThread:57604 [file_pusher.py:join():150] waiting for file pusher
2022-03-26 17:16:33,872 INFO    Thread-20 :57604 [upload_job.py:push():137] Uploaded file E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\requirements.txt
2022-03-26 17:16:33,874 INFO    Thread-19 :57604 [upload_job.py:push():137] Uploaded file E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\output.log
2022-03-26 17:16:33,877 INFO    Thread-18 :57604 [upload_job.py:push():137] Uploaded file E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\config.yaml
2022-03-26 17:16:33,881 INFO    Thread-21 :57604 [upload_job.py:push():137] Uploaded file E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\wandb-summary.json
2022-03-26 17:16:33,904 INFO    Thread-17 :57604 [upload_job.py:push():137] Uploaded file E:\project\nlp_cnn-main\wandb\run-20220326_171531-3f1joo08\files\conda-environment.yaml
2022-03-26 17:16:34,717 INFO    MainThread:57604 [internal.py:handle_exit():82] Internal process exited
