2022-03-19 22:37:03,817 INFO    MainThread:50276 [internal.py:wandb_internal():92] W&B internal server running at pid: 50276, started at: 2022-03-19 22:37:03.817079
2022-03-19 22:37:03,817 INFO    WriterThread:50276 [datastore.py:open_for_write():77] open: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\run-33exv574.wandb
2022-03-19 22:37:03,828 DEBUG   SenderThread:50276 [sender.py:send():235] send: header
2022-03-19 22:37:03,828 DEBUG   SenderThread:50276 [sender.py:send():235] send: run
2022-03-19 22:37:04,235 INFO    SenderThread:50276 [dir_watcher.py:__init__():169] watching files in: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files
2022-03-19 22:37:04,235 INFO    SenderThread:50276 [sender.py:_start_run_threads():812] run started: 33exv574 with start time 1647700623
2022-03-19 22:37:04,243 DEBUG   SenderThread:50276 [sender.py:send():235] send: summary
2022-03-19 22:37:04,243 INFO    SenderThread:50276 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-03-19 22:37:04,243 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: check_version
2022-03-19 22:37:04,259 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: check_version
2022-03-19 22:37:04,789 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: run_start
2022-03-19 22:37:04,789 DEBUG   HandlerThread:50276 [meta.py:__init__():37] meta init
2022-03-19 22:37:04,789 DEBUG   HandlerThread:50276 [meta.py:__init__():51] meta init done
2022-03-19 22:37:04,789 DEBUG   HandlerThread:50276 [meta.py:probe():211] probe
2022-03-19 22:37:04,821 DEBUG   HandlerThread:50276 [meta.py:_save_pip():55] save pip
2022-03-19 22:37:04,821 DEBUG   HandlerThread:50276 [meta.py:_save_pip():69] save pip done
2022-03-19 22:37:04,821 DEBUG   HandlerThread:50276 [meta.py:_save_conda():76] save conda
2022-03-19 22:37:05,239 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_created():217] file/dir created: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\conda-environment.yaml
2022-03-19 22:37:05,239 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_created():217] file/dir created: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\requirements.txt
2022-03-19 22:37:05,239 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_created():217] file/dir created: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\wandb-summary.json
2022-03-19 22:37:06,606 DEBUG   HandlerThread:50276 [meta.py:_save_conda():86] save conda done
2022-03-19 22:37:06,606 DEBUG   HandlerThread:50276 [meta.py:probe():249] probe done
2022-03-19 22:37:06,606 DEBUG   SenderThread:50276 [sender.py:send():235] send: files
2022-03-19 22:37:06,606 INFO    SenderThread:50276 [sender.py:_save_file():947] saving file wandb-metadata.json with policy now
2022-03-19 22:37:06,619 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:37:06,620 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:37:06,959 DEBUG   SenderThread:50276 [sender.py:send():235] send: telemetry
2022-03-19 22:37:07,258 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\conda-environment.yaml
2022-03-19 22:37:07,258 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_created():217] file/dir created: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log
2022-03-19 22:37:07,258 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_created():217] file/dir created: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\wandb-metadata.json
2022-03-19 22:37:07,847 INFO    Thread-16 :50276 [upload_job.py:push():137] Uploaded file C:\Users\chris\AppData\Local\Temp\tmpmwuo72irwandb\lxxrp3xv-wandb-metadata.json
2022-03-19 22:37:09,291 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log
2022-03-19 22:37:17,365 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log
2022-03-19 22:37:19,381 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log
2022-03-19 22:37:21,393 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log
2022-03-19 22:37:22,075 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:37:22,075 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:37:23,412 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log
2022-03-19 22:37:25,433 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log
2022-03-19 22:37:35,530 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\config.yaml
2022-03-19 22:37:36,471 DEBUG   SenderThread:50276 [sender.py:send():235] send: stats
2022-03-19 22:37:37,507 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:37:37,508 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:37:52,862 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:37:52,862 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:37:53,696 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log
2022-03-19 22:38:01,788 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log
2022-03-19 22:38:08,258 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:38:08,258 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:38:10,328 DEBUG   SenderThread:50276 [sender.py:send():235] send: stats
2022-03-19 22:38:17,941 INFO    Thread-12 :50276 [dir_watcher.py:_on_file_modified():230] file/dir modified: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log
2022-03-19 22:38:23,643 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:38:23,643 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:38:38,966 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:38:38,966 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:38:44,241 DEBUG   SenderThread:50276 [sender.py:send():235] send: stats
2022-03-19 22:38:54,363 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:38:54,364 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:39:09,666 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:39:09,668 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:39:18,002 DEBUG   SenderThread:50276 [sender.py:send():235] send: stats
2022-03-19 22:39:25,057 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:39:25,057 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:39:40,465 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:39:40,466 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:39:51,604 DEBUG   SenderThread:50276 [sender.py:send():235] send: stats
2022-03-19 22:39:55,801 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:39:55,801 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:40:11,161 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:40:11,161 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:40:25,302 DEBUG   SenderThread:50276 [sender.py:send():235] send: stats
2022-03-19 22:40:26,535 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:40:26,536 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:40:41,918 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:40:41,918 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:40:57,274 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:40:57,276 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:40:59,005 DEBUG   SenderThread:50276 [sender.py:send():235] send: stats
2022-03-19 22:41:12,638 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:41:12,640 DEBUG   SenderThread:50276 [sender.py:send_request():249] send_request: stop_status
2022-03-19 22:41:16,220 ERROR   SenderThread:50276 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\app\conda\envs\pytorch\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\app\conda\envs\pytorch\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\app\conda\envs\pytorch\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\app\conda\envs\pytorch\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\app\conda\envs\pytorch\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\wandb\sdk\internal\internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "D:\app\conda\envs\pytorch\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2022-03-19 22:41:29,443 WARNING FileStreamThread:50276 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/8christmas8/nlp_cnn/33exv574/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x00000148B6BE17F0>>, args: ('https://api.wandb.ai/files/8christmas8/nlp_cnn/33exv574/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-19 22:41:31,643 WARNING FileStreamThread:50276 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/8christmas8/nlp_cnn/33exv574/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x00000148B6BE17F0>>, args: ('https://api.wandb.ai/files/8christmas8/nlp_cnn/33exv574/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-19 22:41:32,658 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:41:35,787 WARNING FileStreamThread:50276 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/8christmas8/nlp_cnn/33exv574/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x00000148B6BE17F0>>, args: ('https://api.wandb.ai/files/8christmas8/nlp_cnn/33exv574/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-19 22:41:45,437 WARNING FileStreamThread:50276 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/8christmas8/nlp_cnn/33exv574/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x00000148B6BE17F0>>, args: ('https://api.wandb.ai/files/8christmas8/nlp_cnn/33exv574/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-19 22:41:52,679 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:42:04,654 WARNING FileStreamThread:50276 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/8christmas8/nlp_cnn/33exv574/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x00000148B6BE17F0>>, args: ('https://api.wandb.ai/files/8christmas8/nlp_cnn/33exv574/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-19 22:42:12,693 DEBUG   HandlerThread:50276 [handler.py:handle_request():141] handle_request: stop_status
2022-03-19 22:42:24,004 WARNING MainThread:50276 [internal.py:wandb_internal():155] Internal process interrupt: 1
2022-03-19 22:42:28,051 WARNING MainThread:50276 [internal.py:is_dead():387] Internal process exiting, parent pid 50800 disappeared
2022-03-19 22:42:28,051 ERROR   MainThread:50276 [internal.py:wandb_internal():151] Internal process shutdown.
2022-03-19 22:42:28,374 INFO    WriterThread:50276 [datastore.py:close():281] close: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\run-33exv574.wandb
2022-03-19 22:42:28,481 INFO    HandlerThread:50276 [handler.py:finish():778] shutting down handler
2022-03-19 22:42:37,090 WARNING FileStreamThread:50276 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/8christmas8/nlp_cnn/33exv574/file_stream (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). func: <bound method Session.post of <requests.sessions.Session object at 0x00000148B6BE17F0>>, args: ('https://api.wandb.ai/files/8christmas8/nlp_cnn/33exv574/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-19 22:43:39,733 INFO    SenderThread:50276 [sender.py:finish():1078] shutting down sender
2022-03-19 22:43:39,733 INFO    SenderThread:50276 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-19 22:43:40,718 INFO    SenderThread:50276 [dir_watcher.py:finish():313] scan: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files
2022-03-19 22:43:40,718 INFO    SenderThread:50276 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\conda-environment.yaml conda-environment.yaml
2022-03-19 22:43:40,718 INFO    SenderThread:50276 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\config.yaml config.yaml
2022-03-19 22:43:40,718 INFO    SenderThread:50276 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log output.log
2022-03-19 22:43:40,735 INFO    SenderThread:50276 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\requirements.txt requirements.txt
2022-03-19 22:43:40,735 INFO    SenderThread:50276 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\wandb-metadata.json wandb-metadata.json
2022-03-19 22:43:40,742 INFO    SenderThread:50276 [dir_watcher.py:finish():327] scan save: E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\wandb-summary.json wandb-summary.json
2022-03-19 22:43:40,750 INFO    SenderThread:50276 [file_pusher.py:finish():145] shutting down file pusher
2022-03-19 22:43:40,750 INFO    SenderThread:50276 [file_pusher.py:join():150] waiting for file pusher
2022-03-19 22:43:41,551 INFO    Thread-21 :50276 [upload_job.py:push():137] Uploaded file E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\wandb-summary.json
2022-03-19 22:43:41,584 INFO    Thread-17 :50276 [upload_job.py:push():137] Uploaded file E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\conda-environment.yaml
2022-03-19 22:43:41,617 INFO    Thread-19 :50276 [upload_job.py:push():137] Uploaded file E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\output.log
2022-03-19 22:43:41,617 INFO    Thread-20 :50276 [upload_job.py:push():137] Uploaded file E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\requirements.txt
2022-03-19 22:43:41,617 INFO    Thread-18 :50276 [upload_job.py:push():137] Uploaded file E:\project\nlp_cnn-main\wandb\run-20220319_223702-33exv574\files\config.yaml
2022-03-19 22:43:48,082 INFO    MainThread:50276 [internal.py:handle_exit():82] Internal process exited
